// @ts-check
const { test, expect } = require('@playwright/test');

const BASE = process.env.BASE_URL || 'http://localhost:3000';
const URL  = `${BASE}/tools/text-stats/`;

// ── Fixed test inputs with pre-verified expected values ──

// 'hello' → words:1, chars:5, charsNoSpace:5, lines:1, sentences:0, paragraphs:1
const ONE_WORD = 'hello';

// 'hello world' → words:2, chars:11, charsNoSpace:10, lines:1, sentences:0, paragraphs:1
const TWO_WORDS = 'hello world';

// 'one two three four five' → words:5
const FIVE_WORDS = 'one two three four five';

// 'Hi. Bye. Done.' → sentences:3
const THREE_SENTENCES = 'Hi. Bye. Done.';

// 'a\nb\nc' → lines:3
const THREE_LINES = 'a\nb\nc';

// 'block one text.\n\nblock two text.' → paragraphs:2
const TWO_PARAS = 'block one text.\n\nblock two text.';

// 'cat cat cat dog dog bird' → cat×3, dog×2, bird×1
const FREQ_TEXT = 'cat cat cat dog dog bird';

// ~200 words for reading time test (generated by repeat)
const READING_200 = Array(40).fill('hello world foo bar baz').join(' ');
// 40 groups × 5 words = 200 words → 60 sec → "1 min"

// ── 1. Smoke Tests ─────────────────────────────────────────────────────────
test.describe('Text Statistics — smoke', () => {
    test('page title is Text Statistics', async ({ page }) => {
        await page.goto(URL);
        await expect(page).toHaveTitle(/Text Statistics/i);
    });

    test('h1 contains Text Statistics', async ({ page }) => {
        await page.goto(URL);
        await expect(page.locator('h1')).toContainText('Text Statistics');
    });

    test('no JS errors on load', async ({ page }) => {
        const errors = [];
        page.on('pageerror', e => errors.push(e.message));
        await page.goto(URL);
        expect(errors).toHaveLength(0);
    });

    test('no CSP violations on load', async ({ page }) => {
        const violations = [];
        page.on('console', msg => {
            if (msg.type() === 'error' && msg.text().toLowerCase().includes('content security policy')) {
                violations.push(msg.text());
            }
        });
        await page.goto(URL);
        expect(violations).toHaveLength(0);
    });

    test('nav breadcrumb visible', async ({ page }) => {
        await page.goto(URL);
        await expect(page.locator('nav')).toBeVisible();
        await expect(page.locator('nav')).toContainText('Ravionus');
        await expect(page.locator('nav')).toContainText('Tools');
        await expect(page.locator('nav')).toContainText('Text Statistics');
    });

    test('text input textarea is visible', async ({ page }) => {
        await page.goto(URL);
        await expect(page.locator('#textInput')).toBeVisible();
    });

    test('Sample button is visible', async ({ page }) => {
        await page.goto(URL);
        await expect(page.locator('#btnSample')).toBeVisible();
    });

    test('Clear button is visible', async ({ page }) => {
        await page.goto(URL);
        await expect(page.locator('#btnClear')).toBeVisible();
    });

    test('Copy Stats button is visible', async ({ page }) => {
        await page.goto(URL);
        await expect(page.locator('#btnCopyStats')).toBeVisible();
    });

    test('stats pane is visible on desktop', async ({ page }) => {
        await page.goto(URL);
        await expect(page.locator('#paneStats')).toBeVisible();
    });
});

// ── 2. Word Counting ───────────────────────────────────────────────────────
test.describe('Text Statistics — word counting', () => {
    test('empty input shows 0 words', async ({ page }) => {
        await page.goto(URL);
        await page.evaluate(() => localStorage.clear());
        await page.reload();
        await expect(page.locator('#statWords')).toHaveText('0');
    });

    test('single word gives 1', async ({ page }) => {
        await page.goto(URL);
        await page.locator('#textInput').fill(ONE_WORD);
        await expect(page.locator('#statWords')).toHaveText('1');
    });

    test('two words gives 2', async ({ page }) => {
        await page.goto(URL);
        await page.locator('#textInput').fill(TWO_WORDS);
        await expect(page.locator('#statWords')).toHaveText('2');
    });

    test('five words gives 5', async ({ page }) => {
        await page.goto(URL);
        await page.locator('#textInput').fill(FIVE_WORDS);
        await expect(page.locator('#statWords')).toHaveText('5');
    });

    test('words separated by multiple spaces counted correctly', async ({ page }) => {
        await page.goto(URL);
        await page.locator('#textInput').fill('foo  bar  baz');
        await expect(page.locator('#statWords')).toHaveText('3');
    });

    test('stats update without pressing any button', async ({ page }) => {
        await page.goto(URL);
        await expect(page.locator('#statWords')).toHaveText('0');
        await page.locator('#textInput').fill(FIVE_WORDS);
        await expect(page.locator('#statWords')).toHaveText('5');
    });
});

// ── 3. Character Counting ──────────────────────────────────────────────────
test.describe('Text Statistics — character counting', () => {
    test('empty input shows 0 characters', async ({ page }) => {
        await page.goto(URL);
        await page.evaluate(() => localStorage.clear());
        await page.reload();
        await expect(page.locator('#statChars')).toHaveText('0');
    });

    test('"hello" → 5 characters', async ({ page }) => {
        await page.goto(URL);
        await page.locator('#textInput').fill(ONE_WORD);
        await expect(page.locator('#statChars')).toHaveText('5');
    });

    test('"hello world" → 11 characters', async ({ page }) => {
        await page.goto(URL);
        await page.locator('#textInput').fill(TWO_WORDS);
        await expect(page.locator('#statChars')).toHaveText('11');
    });

    test('"hello" → 5 no-space chars (no spaces)', async ({ page }) => {
        await page.goto(URL);
        await page.locator('#textInput').fill(ONE_WORD);
        await expect(page.locator('#statCharsNoSpace')).toHaveText('5');
    });

    test('"hello world" → 10 no-space chars (one space)', async ({ page }) => {
        await page.goto(URL);
        await page.locator('#textInput').fill(TWO_WORDS);
        await expect(page.locator('#statCharsNoSpace')).toHaveText('10');
    });
});

// ── 4. Lines, Sentences, Paragraphs ───────────────────────────────────────
test.describe('Text Statistics — lines, sentences, paragraphs', () => {
    test('single-line text shows 1 line', async ({ page }) => {
        await page.goto(URL);
        await page.locator('#textInput').fill(ONE_WORD);
        await expect(page.locator('#statLines')).toHaveText('1');
    });

    test('three newlines gives 3 lines', async ({ page }) => {
        await page.goto(URL);
        await page.locator('#textInput').fill(THREE_LINES);
        await expect(page.locator('#statLines')).toHaveText('3');
    });

    test('text without sentence-ending punctuation shows 0 sentences', async ({ page }) => {
        await page.goto(URL);
        await page.locator('#textInput').fill('hello world');
        await expect(page.locator('#statSentences')).toHaveText('0');
    });

    test('"Hi. Bye. Done." → 3 sentences', async ({ page }) => {
        await page.goto(URL);
        await page.locator('#textInput').fill(THREE_SENTENCES);
        await expect(page.locator('#statSentences')).toHaveText('3');
    });

    test('text with ! and ? counts sentences', async ({ page }) => {
        await page.goto(URL);
        await page.locator('#textInput').fill('Hello! How are you? Fine.');
        await expect(page.locator('#statSentences')).toHaveText('3');
    });

    test('single block (no blank lines) is 1 paragraph', async ({ page }) => {
        await page.goto(URL);
        await page.locator('#textInput').fill('This is one paragraph.');
        await expect(page.locator('#statParagraphs')).toHaveText('1');
    });

    test('two blank-line-separated blocks are 2 paragraphs', async ({ page }) => {
        await page.goto(URL);
        await page.locator('#textInput').fill(TWO_PARAS);
        await expect(page.locator('#statParagraphs')).toHaveText('2');
    });

    test('empty input shows 0 paragraphs', async ({ page }) => {
        await page.goto(URL);
        await page.evaluate(() => localStorage.clear());
        await page.reload();
        await expect(page.locator('#statParagraphs')).toHaveText('0');
    });
});

// ── 5. Reading Time ────────────────────────────────────────────────────────
test.describe('Text Statistics — reading time', () => {
    test('empty input shows — for reading time', async ({ page }) => {
        await page.goto(URL);
        await page.evaluate(() => localStorage.clear());
        await page.reload();
        await expect(page.locator('#statReadingTime')).toHaveText('—');
    });

    test('short text (few words) shows seconds', async ({ page }) => {
        await page.goto(URL);
        await page.locator('#textInput').fill('hello world foo');
        await expect(page.locator('#statReadingTime')).toContainText('sec');
    });

    test('~200 words shows 1 min reading time', async ({ page }) => {
        await page.goto(URL);
        await page.locator('#textInput').fill(READING_200);
        await expect(page.locator('#statReadingTime')).toContainText('min');
    });

    test('reading time element is visible', async ({ page }) => {
        await page.goto(URL);
        await expect(page.locator('#statReadingTime')).toBeVisible();
    });
});

// ── 6. Character Breakdown ─────────────────────────────────────────────────
test.describe('Text Statistics — character breakdown', () => {
    test('"hello" → 5 letters', async ({ page }) => {
        await page.goto(URL);
        await page.locator('#textInput').fill('hello');
        await expect(page.locator('#statLetters')).toHaveText('5');
    });

    test('"abc123" → 3 letters and 3 digits', async ({ page }) => {
        await page.goto(URL);
        await page.locator('#textInput').fill('abc123');
        await expect(page.locator('#statLetters')).toHaveText('3');
        await expect(page.locator('#statDigits')).toHaveText('3');
    });

    test('"hello world" → 1 space', async ({ page }) => {
        await page.goto(URL);
        await page.locator('#textInput').fill('hello world');
        await expect(page.locator('#statSpaces')).toHaveText('1');
    });

    test('"hello, world!" → 2 punctuation chars', async ({ page }) => {
        await page.goto(URL);
        await page.locator('#textInput').fill('hello, world!');
        await expect(page.locator('#statPunctuation')).toHaveText('2');
    });

    test('empty input → all breakdown stats = 0', async ({ page }) => {
        await page.goto(URL);
        await page.evaluate(() => localStorage.clear());
        await page.reload();
        await expect(page.locator('#statLetters')).toHaveText('0');
        await expect(page.locator('#statDigits')).toHaveText('0');
        await expect(page.locator('#statSpaces')).toHaveText('0');
        await expect(page.locator('#statPunctuation')).toHaveText('0');
    });
});

// ── 7. Word Frequency ──────────────────────────────────────────────────────
test.describe('Text Statistics — word frequency', () => {
    test('repeated word appears in frequency chart', async ({ page }) => {
        await page.goto(URL);
        await page.locator('#textInput').fill(FREQ_TEXT);
        await expect(page.locator('#freqChart')).toContainText('cat');
    });

    test('most frequent word listed first', async ({ page }) => {
        await page.goto(URL);
        await page.locator('#textInput').fill(FREQ_TEXT); // cat×3, dog×2, bird×1
        const firstWord = await page.locator('#freqChart .freq-word').first().textContent();
        expect(firstWord).toBe('cat');
    });

    test('count shown next to word', async ({ page }) => {
        await page.goto(URL);
        await page.locator('#textInput').fill(FREQ_TEXT);
        const firstCount = await page.locator('#freqChart .freq-count').first().textContent();
        expect(firstCount).toBe('3');
    });

    test('empty input shows placeholder message', async ({ page }) => {
        await page.goto(URL);
        await page.evaluate(() => localStorage.clear());
        await page.reload();
        await expect(page.locator('#freqChart')).toContainText('Type something');
    });

    test('stopword toggle checkbox is present', async ({ page }) => {
        await page.goto(URL);
        await expect(page.locator('#ignoreStopWords')).toBeVisible();
    });

    test('ignoring stopwords removes common words from chart', async ({ page }) => {
        await page.goto(URL);
        // Fill with content containing stopwords
        await page.locator('#textInput').fill('the cat the cat sat on the mat');
        // 'the' appears 3 times and is a stopword
        // Without ignore: 'the' should be top
        const topBefore = await page.locator('#freqChart .freq-word').first().textContent();
        expect(topBefore).toBe('the');

        // Enable stopword filtering
        await page.check('#ignoreStopWords');
        // 'the' should no longer be top
        const topAfter = await page.locator('#freqChart .freq-word').first().textContent();
        expect(topAfter).not.toBe('the');
    });
});

// ── 8. Toolbar ─────────────────────────────────────────────────────────────
test.describe('Text Statistics — toolbar', () => {
    test('Sample button fills the textarea', async ({ page }) => {
        await page.goto(URL);
        await page.evaluate(() => localStorage.clear());
        await page.reload();
        await page.click('#btnSample');
        const val = await page.inputValue('#textInput');
        expect(val.trim().length).toBeGreaterThan(20);
    });

    test('Sample button updates word count', async ({ page }) => {
        await page.goto(URL);
        await page.evaluate(() => localStorage.clear());
        await page.reload();
        await page.click('#btnSample');
        const words = await page.locator('#statWords').textContent();
        expect(parseInt(words, 10)).toBeGreaterThan(0);
    });

    test('Clear button empties the textarea', async ({ page }) => {
        await page.goto(URL);
        await page.locator('#textInput').fill(FIVE_WORDS);
        await page.click('#btnClear');
        const val = await page.inputValue('#textInput');
        expect(val).toBe('');
    });

    test('Clear button resets word count to 0', async ({ page }) => {
        await page.goto(URL);
        await page.locator('#textInput').fill(FIVE_WORDS);
        await expect(page.locator('#statWords')).toHaveText('5');
        await page.click('#btnClear');
        await expect(page.locator('#statWords')).toHaveText('0');
    });

    test('Clear button resets all stats to 0', async ({ page }) => {
        await page.goto(URL);
        await page.locator('#textInput').fill(FIVE_WORDS);
        await page.click('#btnClear');
        await expect(page.locator('#statChars')).toHaveText('0');
        await expect(page.locator('#statLines')).toHaveText('0');
    });

    test('Copy Stats copies text containing "Words"', async ({ page }) => {
        await page.goto(URL);
        await page.context().grantPermissions(['clipboard-read', 'clipboard-write']);
        await page.locator('#textInput').fill(FIVE_WORDS);
        // Wait for debounce to fire before copying
        await expect(page.locator('#statWords')).toHaveText('5');
        await page.click('#btnCopyStats');
        const clip = await page.evaluate(() => navigator.clipboard.readText());
        expect(clip).toContain('Words');
        expect(clip).toContain('5');
    });

    test('Copy Stats copies reading time', async ({ page }) => {
        await page.goto(URL);
        await page.context().grantPermissions(['clipboard-read', 'clipboard-write']);
        await page.locator('#textInput').fill(FIVE_WORDS);
        // Wait for debounce to fire before copying
        await expect(page.locator('#statWords')).toHaveText('5');
        await page.click('#btnCopyStats');
        const clip = await page.evaluate(() => navigator.clipboard.readText());
        expect(clip).toContain('Reading time');
    });

    test('no dialog fired on any toolbar action', async ({ page }) => {
        await page.goto(URL);
        let dialogFired = false;
        page.on('dialog', () => { dialogFired = true; });
        await page.locator('#textInput').fill(FIVE_WORDS);
        await page.click('#btnClear');
        await page.click('#btnSample');
        await page.click('#btnCopyStats');
        expect(dialogFired).toBeFalsy();
    });
});

// ── 9. Unique Words ────────────────────────────────────────────────────────
test.describe('Text Statistics — unique words', () => {
    test('all distinct words → unique = total', async ({ page }) => {
        await page.goto(URL);
        await page.locator('#textInput').fill('alpha beta gamma');
        await expect(page.locator('#statUniqueWords')).toHaveText('3');
    });

    test('repeated words reduce unique count', async ({ page }) => {
        await page.goto(URL);
        await page.locator('#textInput').fill('cat cat cat dog');
        // unique: cat, dog = 2
        await expect(page.locator('#statUniqueWords')).toHaveText('2');
    });

    test('unique words section is visible', async ({ page }) => {
        await page.goto(URL);
        await expect(page.locator('#statUniqueWords')).toBeVisible();
    });
});

// ── 10. Input Footer ───────────────────────────────────────────────────────
test.describe('Text Statistics — input footer', () => {
    test('footer shows character and word count', async ({ page }) => {
        await page.goto(URL);
        await page.locator('#textInput').fill('hello world');
        await expect(page.locator('#inputFooter')).toContainText('11');
        await expect(page.locator('#inputFooter')).toContainText('2');
    });

    test('footer updates when text changes', async ({ page }) => {
        await page.goto(URL);
        await page.evaluate(() => localStorage.clear());
        await page.reload();
        await expect(page.locator('#inputFooter')).toContainText('0');
        await page.locator('#textInput').fill(FIVE_WORDS);
        await expect(page.locator('#inputFooter')).toContainText('5');
    });
});

// ── 11. localStorage ───────────────────────────────────────────────────────
test.describe('Text Statistics — localStorage', () => {
    test('typed text persists after reload', async ({ page }) => {
        await page.goto(URL);
        await page.evaluate(() => localStorage.clear());
        await page.reload();
        await page.locator('#textInput').fill(FIVE_WORDS);
        await page.waitForTimeout(400); // allow debounce
        await page.reload();
        const val = await page.inputValue('#textInput');
        expect(val).toBe(FIVE_WORDS);
    });

    test('stats auto-computed from stored text on reload', async ({ page }) => {
        await page.goto(URL);
        await page.evaluate((k) => localStorage.setItem(k, 'hello world'), 'ravionus_tool_text_stats');
        await page.reload();
        await expect(page.locator('#statWords')).toHaveText('2');
    });

    test('cleared text reflected in localStorage', async ({ page }) => {
        await page.goto(URL);
        await page.locator('#textInput').fill(FIVE_WORDS);
        await page.waitForTimeout(400);
        await page.click('#btnClear');
        await page.waitForTimeout(400);
        const saved = await page.evaluate(() => localStorage.getItem('ravionus_tool_text_stats'));
        expect(saved ?? '').toBe('');
    });
});

// ── 12. Mobile Tabs ────────────────────────────────────────────────────────
test.describe('Text Statistics — mobile tabs', () => {
    test.use({ viewport: { width: 375, height: 812 } });

    test('input pane visible by default on mobile', async ({ page }) => {
        await page.goto(URL);
        await expect(page.locator('#paneInput')).toBeVisible();
    });

    test('stats pane hidden by default on mobile', async ({ page }) => {
        await page.goto(URL);
        await expect(page.locator('#paneStats')).not.toBeVisible();
    });

    test('clicking Stats tab shows stats pane', async ({ page }) => {
        await page.goto(URL);
        await page.click('#tabOutput');
        await expect(page.locator('#paneStats')).toBeVisible();
    });

    test('clicking Input tab restores input pane', async ({ page }) => {
        await page.goto(URL);
        await page.click('#tabOutput');
        await page.click('#tabInput');
        await expect(page.locator('#paneInput')).toBeVisible();
        await expect(page.locator('#paneStats')).not.toBeVisible();
    });
});
